# ARM Deployment Action
name: 'ARM Action'
description: 'Automate your GitHub workflows using Azure CLI scripts to deploy ARM Templates.'
inputs:
  inlineScript:
    description: 'Specify the script here'
    required: true
  azcliversion:
    description: 'Azure CLI version to be used to execute the script. If not provided, latest version is used'
    required: false
    default: 'latest'
branding:
  icon: 'activity.svg'
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/main.js'
